# Development
# This is a template for how your development.yml.enc file should look like
telegram:
  bot: INSERT DEVELOPMENT ELEGRAM BOT TOKEN HERE
  news_api: https://INSERT/API/LINK/HERE
  route_param: XXXXXXXX # insert random generated string here for routing
