# Production
# This is a template for how your production.yml.enc file should look like
telegram:
  bot: INSERT PRODUCTION TELEGRAM BOT TOKEN HERE
  news_api: https://INSERT/API/LINK/HERE
  # Type the below on your browser to set webhook. Fill in the respective fields.
  # https://api.telegram.org/bot<INSERT BOT TOKEN>/setWebhook?url=https://<LINK FOR HANDLING WEBHOOKS>/webhooks/<INSERT route_param here>
  route_param: INSERT RANDOM STRING HERE THAT MATCHES THE WEBHOOK SETTING ABOVE
